import { initializeApp, getApps, deleteApp } from 'firebase/app';
import { 
  getAuth, 
  signInWithEmailAndPassword, 
  signOut, 
  createUserWithEmailAndPassword, 
  onAuthStateChanged,
  User as FirebaseUser
} from 'firebase/auth';
import { 
  getFirestore, 
  doc, 
  setDoc, 
  getDoc, 
  collection, 
  addDoc, 
  getDocs, 
  onSnapshot, 
  query, 
  orderBy,
  limit,
  updateDoc,
  deleteDoc
} from 'firebase/firestore';

// Vite environment variables for Firebase configuration
const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID,
};

// Check if Firebase keys are fully configured
const isFirebaseConfigured = !!(
  firebaseConfig.apiKey && 
  firebaseConfig.projectId && 
  firebaseConfig.authDomain
);

let app: any;
let auth: any;
let db: any;

if (isFirebaseConfigured) {
  try {
    app = initializeApp(firebaseConfig);
    auth = getAuth(app);
    db = getFirestore(app);
    console.log("Firebase initialized successfully.");
  } catch (error) {
    console.error("Firebase initialization failed:", error);
  }
} else {
  console.log("Firebase credentials not detected. Operating in High-Fidelity Local Mock Mode.");
}

// ── Types ──
export interface UserProfile {
  uid: string;
  name: string;
  email: string;
  role: 'superadmin' | 'admin' | 'staff';
  phone?: string;
  createdAt: string;
}

export interface Employee {
  id: string;
  name: string;
  email: string;
  role: 'Admin' | 'Staff';
  phone: string;
  salary?: string;
  status: 'Active' | 'Inactive';
}

export interface Bill {
  id: string;
  customerName: string;
  amount: number;
  status: 'completed' | 'pending';
  date: string;
  createdBy?: string;
  invoiceNumber?: string;
}

export interface DailyReportData {
  date: string;
  revenue: number;
  expenses: number;
  profit: number;
  invoices: number;
}

// ── Mock Database Local Storage Key Constants ──
const MOCK_USERS_KEY = 'mock_fb_users';
const MOCK_EMPLOYEES_KEY = 'mock_fb_employees';
const MOCK_BILLS_KEY = 'mock_fb_bills';
const MOCK_DAILY_REPORTS_KEY = 'mock_fb_daily_reports';

// ── Pre-populate Mock Database ──
const initializeMockData = () => {
  // Clear any pre-existing dummy mock data on load
  const isReset = localStorage.getItem('mock_data_reset_v3');
  if (!isReset) {
    localStorage.removeItem(MOCK_EMPLOYEES_KEY);
    localStorage.removeItem(MOCK_BILLS_KEY);
    localStorage.removeItem(MOCK_DAILY_REPORTS_KEY);
    localStorage.setItem('mock_data_reset_v3', 'true');
  }

  if (!localStorage.getItem(MOCK_USERS_KEY)) {
    const defaultUsers: UserProfile[] = [
      {
        uid: 'mock-superadmin-uid',
        name: 'Super Admin',
        email: 'superadmin@photobill.com',
        role: 'superadmin',
        createdAt: new Date().toISOString()
      },
      {
        uid: 'mock-admin-uid',
        name: 'Billing Manager',
        email: 'admin@photobill.com',
        role: 'admin',
        createdAt: new Date().toISOString()
      }
    ];
    localStorage.setItem(MOCK_USERS_KEY, JSON.stringify(defaultUsers));
  }

  if (!localStorage.getItem(MOCK_EMPLOYEES_KEY)) {
    // Pre-populate with default system users so their info shows up in Bill Generated By card
    const defaultEmployees: Employee[] = [
      {
        id: 'mock-superadmin-uid',
        name: 'Super Admin',
        email: 'superadmin@photobill.com',
        role: 'Admin',
        phone: '',
        status: 'Active'
      },
      {
        id: 'mock-admin-uid',
        name: 'Billing Manager',
        email: 'admin@photobill.com',
        role: 'Admin',
        phone: '',
        status: 'Active'
      }
    ];
    localStorage.setItem(MOCK_EMPLOYEES_KEY, JSON.stringify(defaultEmployees));
  }

  if (!localStorage.getItem(MOCK_BILLS_KEY)) {
    localStorage.setItem(MOCK_BILLS_KEY, JSON.stringify([]));
  }

  if (!localStorage.getItem(MOCK_DAILY_REPORTS_KEY)) {
    localStorage.setItem(MOCK_DAILY_REPORTS_KEY, JSON.stringify([]));
  }
};

initializeMockData();

// Helper to get local storage collections
const getLocalCollection = <T>(key: string): T[] => {
  const data = localStorage.getItem(key);
  return data ? JSON.parse(data) : [];
};

const setLocalCollection = <T>(key: string, data: T[]): void => {
  localStorage.setItem(key, JSON.stringify(data));
};

// ── AUTHENTICATION API ──

export const loginUser = async (email: string, password: string): Promise<UserProfile> => {
  if (isFirebaseConfigured) {
    // 1. Authenticate with Firebase Auth
    // Fallback simple username/email helper for standard demo logins in Firebase
    let targetEmail = email;
    if (!email.includes('@')) {
      targetEmail = email === 'superadmin' ? 'superadmin@photobill.com' : 'admin@photobill.com';
    }
    
    const userCredential = await signInWithEmailAndPassword(auth, targetEmail, password);
    const uid = userCredential.user.uid;
    
    // 2. Fetch User Role from Firestore
    const userDocRef = doc(db, 'users', uid);
    const userDoc = await getDoc(userDocRef);
    
    if (userDoc.exists()) {
      return { uid, ...userDoc.data() } as UserProfile;
    } else {
      // Create user profile on first login with default role based on email if not exists
      const isSuper = targetEmail.includes('superadmin');
      const role = isSuper ? 'superadmin' : 'admin';
      const profile: UserProfile = {
        uid,
        name: isSuper ? 'Super Admin' : 'Billing Manager',
        email: targetEmail,
        role,
        createdAt: new Date().toISOString()
      };
      await setDoc(userDocRef, profile);
      return profile;
    }
  } else {
    // Local Mock Logic
    let cleanEmail = email.trim();
    if (!cleanEmail.includes('@')) {
      cleanEmail = cleanEmail === 'superadmin' ? 'superadmin@photobill.com' : 'admin@photobill.com';
    }

    const users = getLocalCollection<UserProfile>(MOCK_USERS_KEY);
    const foundUser = users.find(u => u.email.toLowerCase() === cleanEmail.toLowerCase());

    if (foundUser) {
      // In mock, let password "123456" or any admin password succeed
      if (password === '123456' || password === 'super123' || password === 'admin123') {
        return foundUser;
      }
    }
    throw new Error('Invalid email/username or password. Try superadmin@photobill.com / 123456');
  }
};

export const logoutUser = async (): Promise<void> => {
  if (isFirebaseConfigured) {
    await signOut(auth);
  }
};

// ── EMPLOYEE MANAGEMENT API ──

const mockEmployeeListeners: ((employees: Employee[]) => void)[] = [];

export const getEmployees = async (callback: (employees: Employee[]) => void): Promise<() => void> => {
  if (isFirebaseConfigured) {
    const q = collection(db, 'employees');
    return onSnapshot(q, (snapshot) => {
      const emps: Employee[] = [];
      snapshot.forEach((doc) => {
        emps.push({ id: doc.id, ...doc.data() } as Employee);
      });
      callback(emps);
    });
  } else {
    mockEmployeeListeners.push(callback);
    // Initial fetch
    const emps = getLocalCollection<Employee>(MOCK_EMPLOYEES_KEY);
    callback(emps);
    return () => {
      const idx = mockEmployeeListeners.indexOf(callback);
      if (idx !== -1) {
        mockEmployeeListeners.splice(idx, 1);
      }
    };
  }
};

export const addEmployee = async (employeeData: Omit<Employee, 'id'>, authPassword?: string): Promise<void> => {
  if (isFirebaseConfigured) {
    // To register employee in Firebase Auth without logging out current Super Admin:
    // Initialize a temporary secondary app
    const secondaryAppName = 'SecondaryAuthRegister_' + Date.now();
    const secApp = initializeApp(firebaseConfig, secondaryAppName);
    const secAuth = getAuth(secApp);
    
    try {
      // 1. Create user in Firebase Auth
      const userCredential = await createUserWithEmailAndPassword(
        secAuth, 
        employeeData.email, 
        authPassword || '123456'
      );
      const uid = userCredential.user.uid;

      // Map role to standard user privilege roles for login
      let mappedRole: 'superadmin' | 'admin' | 'staff' = 'staff';
      const roleLower = employeeData.role.toLowerCase();
      if (roleLower.includes('super')) {
        mappedRole = 'superadmin';
      } else if (roleLower.includes('admin') || roleLower.includes('manager')) {
        mappedRole = 'admin';
      }

      // 2. Save in Firestore users collection
      const newProfile: UserProfile = {
        uid,
        name: employeeData.name,
        email: employeeData.email,
        role: mappedRole,
        createdAt: new Date().toISOString()
      };
      await setDoc(doc(db, 'users', uid), newProfile);

      // 3. Save in Firestore employees collection
      const newEmployee: Employee = {
        id: uid,
        name: employeeData.name,
        email: employeeData.email,
        role: employeeData.role,
        phone: employeeData.phone,
        salary: employeeData.salary,
        status: employeeData.status
      };
      await setDoc(doc(db, 'employees', uid), newEmployee);
    } finally {
      // Delete secondary app instance to clean up
      await deleteApp(secApp);
    }
  } else {
    // Local Mock Logic
    const employees = getLocalCollection<Employee>(MOCK_EMPLOYEES_KEY);
    const newId = 'emp-' + Math.random().toString(36).substr(2, 9);
    const newEmployee: Employee = {
      id: newId,
      ...employeeData
    };
    employees.push(newEmployee);
    setLocalCollection(MOCK_EMPLOYEES_KEY, employees);

    // Map role to standard user privilege roles for login
    let mappedRole: 'superadmin' | 'admin' | 'staff' = 'staff';
    const roleLower = employeeData.role.toLowerCase();
    if (roleLower.includes('super')) {
      mappedRole = 'superadmin';
    } else if (roleLower.includes('admin') || roleLower.includes('manager')) {
      mappedRole = 'admin';
    }

    // Also register mock user login
    const users = getLocalCollection<UserProfile>(MOCK_USERS_KEY);
    users.push({
      uid: newId,
      name: employeeData.name,
      email: employeeData.email,
      role: mappedRole,
      createdAt: new Date().toISOString()
    });
    setLocalCollection(MOCK_USERS_KEY, users);

    // Notify all mock subscription listeners immediately
    mockEmployeeListeners.forEach((cb) => cb(employees));
  }
};

// ── BILLS & SALES INVOICES API ──

export const listenToBills = (callback: (bills: Bill[]) => void): (() => void) => {
  if (isFirebaseConfigured) {
    const q = collection(db, 'bills');
    return onSnapshot(q, (snapshot) => {
      const billsList: Bill[] = [];
      snapshot.forEach((doc) => {
        billsList.push({ id: doc.id, ...doc.data() } as Bill);
      });
      callback(billsList);
    });
  } else {
    // Fallback mock listener
    const trigger = () => {
      const bills = getLocalCollection<Bill>(MOCK_BILLS_KEY);
      callback(bills);
    };
    trigger();
    window.addEventListener('storage', trigger);
    return () => window.removeEventListener('storage', trigger);
  }
};

export const addBillToFirestore = async (billData: Omit<Bill, 'id'>, customId?: string): Promise<void> => {
  const id = customId || 'bill-' + Math.random().toString(36).substr(2, 9);
  if (isFirebaseConfigured) {
    const billDocRef = doc(db, 'bills', id);
    const docSnap = await getDoc(billDocRef);
    const isNew = !docSnap.exists();
    
    await setDoc(billDocRef, billData);
    
    if (isNew) {
      // Auto-update daily reports metrics
      await recordInvoiceInDailyReports(billData.amount, billData.status === 'completed' ? billData.amount : 0, 0);
    }
  } else {
    const bills = getLocalCollection<Bill>(MOCK_BILLS_KEY);
    const existingIndex = bills.findIndex(b => b.id === id);
    const isNew = existingIndex === -1;
    if (!isNew) {
      bills[existingIndex] = { id, ...billData };
    } else {
      bills.push({ id, ...billData });
    }
    setLocalCollection(MOCK_BILLS_KEY, bills);

    if (isNew) {
      // Update mock daily reports
      updateMockDailyReports(billData.amount, 0, billData.date);
    }
  }
};

export const deleteBillFromFirestore = async (id: string): Promise<void> => {
  if (isFirebaseConfigured) {
    try {
      await deleteDoc(doc(db, 'bills', id));
    } catch (err) {
      console.error("Error deleting bill from Firestore:", err);
    }
  } else {
    const bills = getLocalCollection<Bill>(MOCK_BILLS_KEY);
    const filtered = bills.filter(b => b.id !== id);
    setLocalCollection(MOCK_BILLS_KEY, filtered);
  }
};

// ── DAILY REPORT & METRICS API ──

export const listenToDailyReports = (callback: (reports: DailyReportData[]) => void): (() => void) => {
  if (isFirebaseConfigured) {
    const q = query(collection(db, 'dailyReports'), orderBy('date', 'desc'), limit(7));
    return onSnapshot(q, (snapshot) => {
      const reportsList: DailyReportData[] = [];
      snapshot.forEach((doc) => {
        reportsList.push(doc.data() as DailyReportData);
      });
      // Sort ascending for chart rendering
      reportsList.sort((a, b) => a.date.localeCompare(b.date));
      callback(reportsList);
    });
  } else {
    const trigger = () => {
      const reports = getLocalCollection<DailyReportData>(MOCK_DAILY_REPORTS_KEY);
      // Sort ascending for charts
      reports.sort((a, b) => a.date.localeCompare(b.date));
      callback(reports);
    };
    trigger();
    window.addEventListener('storage', trigger);
    return () => window.removeEventListener('storage', trigger);
  }
};

// Synchronize daily reports when adding expenses or purchases
export const addExpenseToFirestore = async (amount: number, dateStr: string): Promise<void> => {
  if (isFirebaseConfigured) {
    const reportRef = doc(db, 'dailyReports', dateStr);
    const reportSnap = await getDoc(reportRef);
    if (reportSnap.exists()) {
      const data = reportSnap.data() as DailyReportData;
      const newExpenses = (data.expenses || 0) + amount;
      await updateDoc(reportRef, {
        expenses: newExpenses,
        profit: (data.revenue || 0) - newExpenses
      });
    } else {
      await setDoc(reportRef, {
        date: dateStr,
        revenue: 0,
        expenses: amount,
        profit: -amount,
        invoices: 0
      });
    }
  } else {
    updateMockDailyReports(0, amount, dateStr);
  }
};

const updateMockDailyReports = (revenue: number, expenses: number, dateStr: string) => {
  const reports = getLocalCollection<DailyReportData>(MOCK_DAILY_REPORTS_KEY);
  const existing = reports.find(r => r.date === dateStr);
  
  if (existing) {
    existing.revenue += revenue;
    existing.expenses += expenses;
    existing.profit = existing.revenue - existing.expenses;
    if (revenue > 0) existing.invoices += 1;
  } else {
    reports.push({
      date: dateStr,
      revenue,
      expenses,
      profit: revenue - expenses,
      invoices: revenue > 0 ? 1 : 0
    });
  }
  
  // Keep last 7 days only or sort
  reports.sort((a, b) => a.date.localeCompare(b.date));
  setLocalCollection(MOCK_DAILY_REPORTS_KEY, reports);
};

const recordInvoiceInDailyReports = async (amount: number, paidAmount: number, expenseAmount: number): Promise<void> => {
  const dateStr = new Date().toISOString().split('T')[0];
  const reportRef = doc(db, 'dailyReports', dateStr);
  const reportSnap = await getDoc(reportRef);

  if (reportSnap.exists()) {
    const data = reportSnap.data() as DailyReportData;
    await updateDoc(reportRef, {
      revenue: (data.revenue || 0) + amount,
      expenses: (data.expenses || 0) + expenseAmount,
      profit: ((data.revenue || 0) + amount) - ((data.expenses || 0) + expenseAmount),
      invoices: (data.invoices || 0) + 1
    });
  } else {
    await setDoc(reportRef, {
      date: dateStr,
      revenue: amount,
      expenses: expenseAmount,
      profit: amount - expenseAmount,
      invoices: 1
    });
  }
};

// Sync whole database helper for initial transition
export const syncInvoicesToFirestore = async (invoices: any[]): Promise<void> => {
  for (const inv of invoices) {
    const billData: Omit<Bill, 'id'> = {
      customerName: inv.customerName,
      amount: inv.totalAmount,
      status: inv.paymentStatus,
      date: inv.createdAt ? inv.createdAt.split('T')[0] : new Date().toISOString().split('T')[0],
      createdBy: inv.createdBy || 'System',
      invoiceNumber: inv.invoiceNumber
    };
    await addBillToFirestore(billData, inv.id);
  }
};

export { isFirebaseConfigured, auth, db };
